Repository palantir/junit-resource-poller, pull requests merged in 2019-08, with the labels that each got.

#7 Upgrade buildscript and project dependencies
  .baseline/checkstyle/checkstyle-suppressions.xml
  .baseline/checkstyle/checkstyle.xml
  .baseline/copyright/001_apache-2.0.txt
  .baseline/eclipse/org.eclipse.jdt.core.prefs
  .baseline/eclipse/static/dotfile.settings/org.eclipse.jdt.ui.prefs
  .baseline/idea/intellij-java-palantir-style.xml
  .circleci/config.yml
  .circleci/template.sh
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  junit-resource-poller/build.gradle
  junit-resource-poller/src/main/java/com/palantir/junit/FailureCachingHttpPollingResource.java
  junit-resource-poller/src/main/java/com/palantir/junit/HttpPollingResource.java
  junit-resource-poller/src/main/java/com/palantir/junit/PollableResource.java
  junit-resource-poller/src/main/java/com/palantir/junit/ResourcePoller.java
  junit-resource-poller/src/test/java/com/palantir/junit/FailureCachingHttpPollingResourceTest.java
  junit-resource-poller/src/test/java/com/palantir/junit/HttpPollingResourceTest.java
  versions.props
Labels: no changelog

#31 Use standard publish-jar.gradle
  .travis.yml
  build.gradle
  gradle/publish-jar.gradle
  gradle/publish.gradle
  junit-resource-poller/build.gradle
Labels: merge when ready, no changelog

#29 Colourful readme
  readme.md
Labels: merge when ready

#33 Fix the builder method visibility
  junit-resource-poller/src/main/java/com/palantir/junit/FailureCachingHttpPollingExtension.java
  junit-resource-poller/src/main/java/com/palantir/junit/FailureCachingHttpPollingResource.java
  junit-resource-poller/src/main/java/com/palantir/junit/HttpPollingBuilder.java
  junit-resource-poller/src/main/java/com/palantir/junit/HttpPollingExtension.java
  junit-resource-poller/src/main/java/com/palantir/junit/HttpPollingResource.java
Labels: autorelease, merge when ready

#41 JUnit5 Support ResourcePoller#poll(PollableResource)
  junit-resource-poller/src/main/java/com/palantir/junit/HttpPollingExtension.java
Labels: autorelease, merge when ready
